import Dress from "../../assets/images/dress.svg"
export let products = {
    products: [
      {
        id: 1,
        title: "Black Winter Jacket",
        description: "Autumn & Winter casual cotton padded jacket.",
        price: 499,
        maxQuantity: 4,
        quantity: 1,
        offer_percentage: 38,
        rating: 4.2,
        review_count: 6890,
        sizes: ["S", "M", "L", "XL"],
        selectedSize: "M",
        details:
          "Stay warm and stylish with this premium black winter jacket crafted from soft cotton fabric. It features a regular fit, full sleeves, and lightweight insulation for maximum comfort. Perfect for daily wear, travel, and outdoor activities during colder seasons.",
        image_url: Dress,
      },
      {
        id: 2,
        title: "Mens Starry Shirt",
        description: "100% cotton printed casual shirt.",
        price: 399,
        maxQuantity: 4,
        quantity: 1,
        offer_percentage: 33,
        rating: 4.0,
        review_count: 152344,
        sizes: ["M", "L", "XL", "XXL"],
        selectedSize: "L",
        details:
          "Made from premium breathable cotton, this printed shirt offers a slim fit with a modern design. The soft fabric ensures all-day comfort while the stylish print makes it ideal for casual outings, parties, and weekend wear.",
        image_url: Dress,
      },
      {
        id: 3,
        title: "Black Party Dress",
        description: "Elegant solid black party dress.",
        price: 2000,
        maxQuantity: 4,
        quantity: 1,
        offer_percentage: 20,
        rating: 4.5,
        review_count: 523456,
        sizes: ["XS", "S", "M", "L"],
        selectedSize: "S",
        details:
          "Turn heads with this elegant black party dress featuring a flattering slim fit and premium polyester fabric. Designed for comfort and style, it is perfect for parties, dinners, and special occasions with a timeless solid finish.",
        image_url: Dress,
      },
      {
        id: 4,
        title: "Pink Embroidered Maxi Dress",
        description: "Beautiful embroidered tiered maxi dress.",
        price: 1900,
        maxQuantity: 4,
        quantity: 1,
        offer_percentage: 21,
        rating: 4.1,
        review_count: 45678,
        sizes: ["S", "M", "L"],
        selectedSize: "M",
        details:
          "This elegant pink maxi dress features intricate embroidery and a flowy silhouette for a graceful look. Crafted from soft rayon fabric, it offers comfort and sophistication, making it perfect for festive occasions and celebrations.",
        image_url: Dress,
      },
      {
        id: 5,
        title: "Floral Flare Dress",
        description: "Floral printed midi dress.",
        price: 1990,
        maxQuantity: 4,
        quantity: 1,
        offer_percentage: 20,
        rating: 4.3,
        review_count: 335566,
        sizes: ["S", "M", "L", "XL"],
        selectedSize: "L",
        details:
          "Designed with vibrant floral prints and a flattering flared silhouette, this midi dress combines elegance and comfort. Lightweight georgette fabric provides a soft feel, making it suitable for brunches, vacations, and casual events.",
        image_url: Dress,
      },
      {
        id: 6,
        title: "Denim Casual Dress",
        description: "Blue cotton denim casual dress.",
        price: 999,
        maxQuantity: 4,
        quantity: 1,
        offer_percentage: 33,
        rating: 3.9,
        review_count: 27344,
        sizes: ["XS", "S", "M", "L"],
        selectedSize: "M",
        details:
          "Crafted from premium denim fabric, this casual dress offers durability with exceptional comfort. The timeless blue finish and relaxed fit make it a versatile choice for everyday wear, shopping trips, and weekend outings.",
        image_url: Dress,
      },
      {
        id: 7,
        title: "Jordan Stay Sneakers",
        description: "Classic basketball-inspired sneakers.",
        price: 4999,
        maxQuantity: 4,
        quantity: 1,
        offer_percentage: 29,
        rating: 4.6,
        review_count: 1023456,
        sizes: ["XS", "S", "M", "L"],
        selectedSize: "M",
        details:
          "Inspired by iconic basketball footwear, these sneakers feature premium leather construction, cushioned soles, and superior grip. Designed for both sports and casual wear, they provide lasting comfort and a stylish appearance.",
        image_url: Dress,
      },
      {
        id: 8,
        title: "Realme 7 Smartphone",
        description: "6GB RAM | 64GB Storage smartphone.",
        price: 13499,
        maxQuantity: 4,
        quantity: 1,
        offer_percentage: 30,
        rating: 4.1,
        review_count: 344567,
        sizes: ["S", "M", "L", "XL"],
        selectedSize: "M",
        details:
          "The Realme 7 delivers smooth performance with its powerful processor, vibrant Full HD+ display, and long-lasting 5000mAh battery. Capture stunning photos with the AI quad-camera setup and enjoy seamless multitasking throughout the day.",
        image_url: Dress,
      },
      {
        id: 9,
        title: "Noise Smart Watch",
        description: "Bluetooth calling smartwatch.",
        price: 2499,
        maxQuantity: 4,
        quantity: 1,
        offer_percentage: 44,
        rating: 4.4,
        review_count: 124567,
        sizes: ["S", "M", "L", "XL"],
        selectedSize: "M",
        details:
          "Stay connected and track your fitness with this stylish smartwatch featuring Bluetooth calling, heart rate monitoring, SpO2 tracking, multiple sports modes, and up to seven days of battery life on a single charge.",
        image_url: Dress,
      },
      {
        id: 10,
        title: "Wildcraft Travel Backpack",
        description: "35L water-resistant backpack.",
        price: 1499,
        maxQuantity: 4,
        quantity: 1,
        offer_percentage: 25,
        rating: 4.3,
        review_count: 87543,
        sizes: ["S", "M", "L", "XL"],
        selectedSize: "M",
        details:
          "Built for everyday use and travel, this 35L backpack features multiple compartments, padded shoulder straps, and water-resistant polyester fabric. It provides ample storage for laptops, books, clothes, and travel essentials while ensuring lasting durability.",
        image_url: Dress,
      },
    ],
  };